---

- name: detect binary file for trivy on {{ trivy_ui_delegate_to }}
  become: false
  delegate_to: "{{ trivy_delegate_to }}"
  ansible.builtin.stat:
    path: "{{ trivy_local_tmp_directory }}/trivy"
  register: stat_file_binary

- name: propagate trivy binaries
  ansible.builtin.copy:
    src: "{{ trivy_local_tmp_directory }}/trivy"
    dest: "{{ trivy_install_path }}/trivy"
    mode: 0755
    owner: "{{ trivy_system_user }}"
    group: "{{ trivy_system_group }}"
    remote_src: "{{ 'true' if trivy_direct_download else 'false' }}"
  when:
    - stat_file_binary.stat.exists

- name: make files executable
  ansible.builtin.file:
    path: "{{ trivy_install_path }}/trivy"
    mode: 0755
    owner: "{{ trivy_system_user }}"
    group: "{{ trivy_system_group }}"

- name: create custom fact file
  bodsch.core.facts:
    name: trivy
    facts:
      version: "{{ trivy_version }}"

- name: create trivy data directory
  ansible.builtin.file:
    state: directory
    path: "{{ trivy_data_dir }}"
    mode: 0770
    owner: "{{ trivy_system_user }}"
    group: "{{ trivy_system_group }}"

- name: create link to binary
  ansible.builtin.file:
    src: "{{ trivy_install_path }}/trivy"
    dest: "/usr/bin/trivy"
    state: link
    force: true
    follow: false
  notify:
    - restart trivy

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/trivy.service.j2"
        dest: "{{ systemd_lib_directory }}/trivy.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart trivy

    - name: create systemd service configuration
      ansible.builtin.template:
        src: "trivy.j2"
        dest: "{{ trivy_defaults_directory }}/trivy"
        force: true
        owner: root
        group: "{{ trivy_system_group }}"
        mode: 0640
      notify:
        - validate config
        - reload trivy

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/trivy.j2"
        dest: "/etc/conf.d/trivy"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init file
      ansible.builtin.template:
        src: "init/openrc/init.d/trivy.j2"
        dest: "/etc/init.d/trivy"
        owner: root
        group: root
        mode: 0750

...
