---

- name: create install directory
  ansible.builtin.file:
    path: "{{ trivy_install_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: detect extracted binary file for trivy on '{{ trivy_delegate_to }}'
  become: false
  delegate_to: "{{ trivy_delegate_to }}"
  run_once: "{{ 'false' if trivy_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ trivy_local_tmp_directory }}/trivy"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed trivy binary
  ansible.builtin.stat:
    path: "{{ trivy_install_path }}/{{ trivy_release.binary }}"
  register: stat_trivy_binary

- name: detect activated trivy binary
  ansible.builtin.stat:
    path: /usr/bin/{{ trivy_release.binary }}
  register: stat_trivy_activated

- name: install and activate trivy
  when:
    - (stat_trivy_binary.stat is defined and not stat_trivy_binary.stat.exists | default('false')) or
      not stat_trivy_activated.stat | bodsch.core.linked_version(trivy_install_path, trivy_version)
  block:
    - name: propagate files
      block:
        - name: propagate trivy binary
          ansible.builtin.copy:
            src: "{{ trivy_local_tmp_directory }}/{{ trivy_release.binary }}"
            dest: "{{ trivy_install_path }}/{{ trivy_release.binary }}"
            mode: "0755"
            owner: root
            group: root
            remote_src: "{{ 'true' if trivy_direct_download else 'false' }}"

        - name: make files executable
          ansible.builtin.file:
            path: "{{ trivy_install_path }}/{{ trivy_release.binary }}"
            mode: "0755"
            owner: root
            group: root

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ trivy_install_path }}/{{ trivy_release.binary }}"
            dest: /usr/bin/{{ trivy_release.binary }}
            state: link
            force: true
            follow: false

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ trivy_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: create custom fact file
  bodsch.core.facts:
    name: trivy
    facts:
      version: "{{ trivy_version }}"

...
