---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: download
  ansible.builtin.include_tasks: download.yml
  when:
    - not stat_trivy_binary.stat.exists

- name: install
  ansible.builtin.include_tasks: install.yml

...
